---
title    : Facets
slogan   : ALL YOUR BASE ARE BELONG TO RUBY!
created  : '2004-12-16'
status   : stable
summary  :
  Premium Core Extensions and Standard Additions

description :
  Facets is a single largest collection of core extension methods
  and standard class additions available for the Ruby programming
  language.

project  : facets
author   : Thomas Sawyer <transfire@gmail.com>
email    : facets-universal@rubyforge.org
homepage : 'http://facets.rubyforge.org'
download : 'http://rubyforge.org/projects/facets'

exclude  : [ work, pkg, site, task, temp ]

hosts:
  rubyforge:
    type: rubyforge
    groupid  : 804
  rubytalk:
    type: rubytalk
  personal:
    type: mailinglist
    mailto: transfire@gmail.com

